### ISSUE TITLE
German

### ISSUE THREAD

**Issue by schergr** [clusterzx/paperless-ai#2]
The metadata is defaulting to german, translating the titles of my documents to German, and also adding tags in german.  Whats going on?

![image](https://github.com/user-attachments/assets/27ebfdf4-cbeb-4435-9ac4-fddd2e0d6fc7)

**Comment by schergr** [comment]
Here is the startup log. Gives no indication until it starts getting into the document catorization
`2024-12-18T14:34:42.060069037Z 2024-12-18T14:34:41: PM2 log: Launching in no daemon mode
2024-12-18T14:34:42.095497912Z 2024-12-18T14:34:42: PM2 log: App [paperless-assistant:0] starting in -cluster mode-
2024-12-18T14:34:42.115070356Z 2024-12-18T14:34:42: PM2 log: App [paperless-assistant:0] online
2024-12-18T14:34:42.358581852Z Server running on port 3000
2024-12-18T14:34:42.362731452Z Setup not completed. Skipping initial scan. Visit http://your-domain-or-ip.com:3000/setup to complete setup.
2024-12-18T14:36:03.937462424Z 2024-12-18T14:36:03: PM2 log: App name:paperless-assistant id:0 disconnected
2024-12-18T14:36:03.939553756Z 2024-12-18T14:36:03: PM2 log: App [paperless-assistant:0] exited with code [0] via signal [SIGINT]
2024-12-18T14:36:03.941253248Z 2024-12-18T14:36:03: PM2 log: App [paperless-assistant:0] will restart in 100ms
2024-12-18T14:36:04.043498721Z 2024-12-18T14:36:04: PM2 log: App [paperless-assistant:0] starting in -cluster mode-
2024-12-18T14:36:04.085356084Z 2024-12-18T14:36:04: PM2 log: App [paperless-assistant:0] online
2024-12-18T14:36:04.280250044Z Server running on port 3000
2024-12-18T14:36:05.875115246Z Running initial scan...
2024-12-18T14:36:05.875150972Z Starting document scan...
2024-12-18T14:36:06.916171787Z Found 0 existing tags
2024-12-18T14:36:07.736600970Z Fetched page 1, got 100 documents. Total so far: 100
2024-12-18T14:36:08.165297458Z Fetched page 2, got 25 documents. Total so far: 125
2024-12-18T14:36:08.165602449Z Processing new document: NIST.SP.1299
2024-12-18T14:36:09.890648804Z Refreshing tag cache...
2024-12-18T14:36:09.923839649Z Tag cache refreshed. Found 0 tags.
2024-12-18T14:36:10.264242776Z Successfully created tag "Cybersecurity" with ID 1
2024-12-18T14:36:10.407278296Z Successfully created tag "Framework" with ID 2
2024-12-18T14:36:10.572692275Z Successfully created tag "NIST" with ID 3
2024-12-18T14:36:10.739694911Z Successfully created tag "Risk Management" with ID 4
2024-12-18T14:36:10.893722268Z Created new correspondent "National Institute of Standards and Technology (NIST)" with ID 1
2024-12-18T14:36:10.953600834Z Current tags for document 86: []
2024-12-18T14:36:10.954257068Z Adding new tags: [ 1, 2, 3, 4 ]
2024-12-18T14:36:10.954584156Z Combined tags: [ 1, 2, 3, 4 ]
2024-12-18T14:36:11.438857601Z Updated document 86 with: {
2024-12-18T14:36:11.438884590Z   tags: [ 1, 2, 3, 4 ],
2024-12-18T14:36:11.438888289Z   title: 'NIST Cybersecurity Framework 2.0: Resource & Overview Guide',
2024-12-18T14:36:11.438891498Z   created: '2024-02-01T00:00:00.000Z',
2024-12-18T14:36:11.438894256Z   correspondent: 1,
2024-12-18T14:36:11.438896885Z   language: 'de'
2024-12-18T14:36:11.438899487Z }
2024-12-18T14:36:11.473073102Z Updated document NIST.SP.1299 with: {
2024-12-18T14:36:11.473107697Z   tags: [ 1, 2, 3, 4 ],
2024-12-18T14:36:11.473111756Z   title: 'NIST Cybersecurity Framework 2.0: Resource & Overview Guide',
2024-12-18T14:36:11.473114522Z   created: '2024-02-01',
2024-12-18T14:36:11.473116626Z   correspondent: 1,
2024-12-18T14:36:11.473118724Z   language: 'de'
2024-12-18T14:36:11.473120782Z }
2024-12-18T14:36:11.473715537Z Document 86 added to processed_documents
2024-12-18T14:36:11.473840775Z Document NIST Cybersecurity Framework 2.0: Resource & Overview Guide processing completed
2024-12-18T14:36:11.473938282Z Processing new document: JOINT-CSI-BEST-PRACTICES-EVENT-LOGGING-THREAT-DETECTION
2024-12-18T14:36:13.653211817Z Found tag "Cybersecurity" in cache with ID 1
2024-12-18T14:36:13.802378032Z Successfully created tag "Event Logging" with ID 5
2024-12-18T14:36:13.946775416Z Successfully created tag "Threat Detection" with ID 6
2024-12-18T14:36:14.100959674Z Successfully created tag "Best Practices" with ID 7
2024-12-18T14:36:14.266927424Z Created new correspondent "Australian Government" with ID 2
2024-12-18T14:36:14.319837552Z Current tags for document 36: []
2024-12-18T14:36:14.319861067Z Adding new tags: [ 1, 5, 6, 7 ]
2024-12-18T14:36:14.319967293Z Combined tags: [ 1, 5, 6, 7 ]
2024-12-18T14:36:14.679988314Z Updated document 36 with: {
2024-12-18T14:36:14.680017705Z   tags: [ 1, 5, 6, 7 ],
2024-12-18T14:36:14.680023966Z   title: 'Best Practices für Ereignisprotokollierung und Bedrohungserkennung',
2024-12-18T14:36:14.680029102Z   created: '2024-01-01T00:00:00.000Z',
2024-12-18T14:36:14.680033317Z   correspondent: 2,
2024-12-18T14:36:14.680037327Z   language: 'de'
2024-12-18T14:36:14.680041356Z }
2024-12-18T14:36:14.727501140Z Updated document JOINT-CSI-BEST-PRACTICES-EVENT-LOGGING-THREAT-DETECTION with: {
2024-12-18T14:36:14.727536252Z   tags: [ 1, 5, 6, 7 ],
2024-12-18T14:36:14.727545692Z   title: 'Best Practices für Ereignisprotokollierung und Bedrohungserkennung',
2024-12-18T14:36:14.727556552Z   created: '2024-01-01',
2024-12-18T14:36:14.727563181Z   correspondent: 2,
2024-12-18T14:36:14.727569563Z   language: 'de'
2024-12-18T14:36:14.727575923Z }
2024-12-18T14:36:14.727701184Z Document 36 added to processed_documents
2024-12-18T14:36:14.727814205Z Document Best Practices für Ereignisprotokollierung und Bedrohungserkennung processing completed
2024-12-18T14:36:14.728007099Z Processing new document: AIDesignLLMs786734
2024-12-18T14:36:16.599887946Z Successfully created tag "Künstliche Intelligenz" with ID 8
2024-12-18T14:36:16.755588599Z Successfully created tag "Sprachmodelle" with ID 9
2024-12-18T14:36:16.929326580Z Successfully created tag "Designmuster" with ID 10
2024-12-18T14:36:17.053373478Z Successfully created tag "Generative KI" with ID 11
2024-12-18T14:36:17.198389846Z Created new correspondent "Gartner, Inc." with ID 3
2024-12-18T14:36:17.260567859Z Current tags for document 31: []
2024-12-18T14:36:17.260731878Z Adding new tags: [ 8, 9, 10, 11 ]
2024-12-18T14:36:17.260984969Z Combined tags: [ 8, 9, 10, 11 ]
2024-12-18T14:36:18.577392246Z Updated document 31 with: {
2024-12-18T14:36:18.577421332Z   tags: [ 8, 9, 10, 11 ],
2024-12-18T14:36:18.577428253Z   title: 'AI Design Patterns für große Sprachmodelle',
2024-12-18T14:36:18.577433877Z   created: '2023-01-01T00:00:00.000Z',
2024-12-18T14:36:18.577438548Z   correspondent: 3,
2024-12-18T14:36:18.577443069Z   language: 'de'
2024-12-18T14:36:18.577449279Z }
2024-12-18T14:36:18.613886846Z Updated document AIDesignLLMs786734 with: {
2024-12-18T14:36:18.613903444Z   tags: [ 8, 9, 10, 11 ],
2024-12-18T14:36:18.613906390Z   title: 'AI Design Patterns für große Sprachmodelle',
2024-12-18T14:36:18.613909262Z   created: '2023-01-01',
2024-12-18T14:36:18.613911947Z   correspondent: 3,
2024-12-18T14:36:18.613914146Z   language: 'de'
2024-12-18T14:36:18.613916294Z }

 `

**Comment by clusterzx** [comment]
Thanks for reporting this issue. I have an idea where the issue is. 
I will get back to you in a couple of minutes.

**Comment by clusterzx** [comment]
Can you delete the cointainer and also remove all tags and correspondents? Then run a new test and pull the new docker image.
It is probally an issue with the system prompt.

**Comment by schergr** [comment]
> Can you delete the cointainer and also remove all tags and correspondents? Then run a new test and pull the new docker image. It is probally an issue with the system prompt.

Alot of the document titles have also been modified.  Is that going to throw off the prompt?

**Comment by clusterzx** [comment]
As soon as you delete the old docker image and pull the new one, the database is empty and it will reiterate through the files.

**Comment by clusterzx** [comment]
Maybe I will implement a language setting to specifically tell the prompt what language is needed. 
As of now the new system prompt that will be appended to your own custom promp looks like this:
```js

        Return the result EXCLUSIVELY as a JSON object. In addition, fill the data according to the language of the original document.:
        
        {
          "title": "Title",
          "correspondent": "Correspondent/Author",
          "tags": ["Tag1", "Tag2", "Tag3", "Tag4"],
          "document_date": "YYYY-MM-DD",
          "language": "en/de/es/..."
        }`;

So it tries to find the language and adapt that to the Tags and Title. With the language setting in the future the prompt will be filled with the user desired language.

**Comment by schergr** [comment]
> Can you delete the cointainer and also remove all tags and correspondents? Then run a new test and pull the new docker image. It is probally an issue with the system prompt.

```
2024-12-18T16:03:22: PM2 log: Launching in no daemon mode
2024-12-18T16:03:22: PM2 log: App [paperless-assistant:0] starting in -cluster mode-
2024-12-18T16:03:22: PM2 log: App [paperless-assistant:0] online
Server running on port 3000
Setup not completed. Skipping initial scan. Visit http://your-domain-or-ip.com:3000/setup to complete setup.
2024-12-18T16:04:37: PM2 log: App name:paperless-assistant id:0 disconnected
2024-12-18T16:04:37: PM2 log: App [paperless-assistant:0] exited with code [0] via signal [SIGINT]
2024-12-18T16:04:37: PM2 log: App [paperless-assistant:0] will restart in 100ms
2024-12-18T16:04:37: PM2 log: App [paperless-assistant:0] starting in -cluster mode-
2024-12-18T16:04:37: PM2 log: App [paperless-assistant:0] online
Server running on port 3000
Running initial scan...
Starting document scan...
Error during document scan: TypeError: Cannot read properties of undefined (reading 'length')
    at scanDocuments (/app/server.js:48:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-12-18T16:05:03: PM2 log: App name:paperless-assistant id:0 disconnected
2024-12-18T16:05:03: PM2 log: App [paperless-assistant:0] exited with code [0] via signal [SIGINT]
2024-12-18T16:05:03: PM2 log: App [paperless-assistant:0] will restart in 150ms
2024-12-18T16:05:03: PM2 log: App [paperless-assistant:0] starting in -cluster mode-
2024-12-18T16:05:03: PM2 log: App [paperless-assistant:0] online
Server running on port 3000
Running initial scan...
Starting document scan...
Error during document scan: TypeError: Cannot read properties of undefined (reading 'length')
    at scanDocuments (/app/server.js:48:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error fetching documents page 2: Cannot read properties of undefined (reading 'length')
Error fetching documents: TypeError: Cannot read properties of undefined (reading 'length')
    at PaperlessService.getAllDocuments (/app/services/paperlessService.js:188:74)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/server.js:122:23
Error fetching documents page 2: Cannot read properties of undefined (reading 'length')
Error fetching documents: TypeError: Cannot read properties of undefined (reading 'length')
    at PaperlessService.getAllDocuments (/app/services/paperlessService.js:188:74)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/server.js:122:23
Error fetching documents page 2: Cannot read properties of undefined (reading 'length')
Error fetching documents: TypeError: Cannot read properties of undefined (reading 'length')
    at PaperlessService.getAllDocuments (/app/services/paperlessService.js:188:74)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/server.js:122:23
2024-12-18T16:05:52: PM2 log: [PM2][WORKER] Reset the restart delay, as app paperless-assistant has been up for more than 30000ms
Error fetching documents page 2: Cannot read properties of undefined (reading 'length')
Error fetching documents: TypeError: Cannot read properties of undefined (reading 'length')
    at PaperlessService.getAllDocuments (/app/services/paperlessService.js:188:74)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/server.js:122:23
```

**Comment by clusterzx** [comment]
The error indicates that the file is to big and the token length is exceeded. 
I defined gpt-4o-mini as desired model. 

Can you give me the prompt you defined in the setup process?

**Comment by schergr** [comment]
I don't have a prompt.  Just yours.
 
> The error indicates that the file is to big and the token length is exceeded. I defined gpt-4o-mini as desired model.
> 
> Can you give me the prompt you defined in the setup process?

**Comment by schergr** [comment]
> I don't have a prompt. Just yours.
> 
> > The error indicates that the file is to big and the token length is exceeded. I defined gpt-4o-mini as desired model.
> > Can you give me the prompt you defined in the setup process?

Shoot...I have a ' in there by accident.

**Comment by schergr** [comment]
> The error indicates that the file is to big and the token length is exceeded. I defined gpt-4o-mini as desired model.
> 
> Can you give me the prompt you defined in the setup process?

Can you make that a config setting?

**Comment by clusterzx** [comment]
> > The error indicates that the file is to big and the token length is exceeded. I defined gpt-4o-mini as desired model.
> > Can you give me the prompt you defined in the setup process?
> 
> Can you make that a config setting?

Sure, I will update the repo in the next few hours.

**Comment by schergr** [comment]
How frequently do you poll for new documents being added?

**Comment by schergr** [comment]
I think it would also be good to have a UI language element as well...
```

      <% documents.forEach(function(doc) { %>
        <div class="document">
          <h3><%= doc.title %></h3>
          <p><strong>Erstellt am:</strong> <%= new Date(doc.created).toLocaleDateString('de-DE') %></p>
          <p><strong>Tags:</strong>
            <% if (doc.tags && doc.tags.length > 0) { %>
              <% doc.tags.forEach(function(tag) { %>
                <span class="tag"><%= tag %></span>
              <% }); %>
            <% } else { %>
              Keine Tags
            <% } %>
          </p>
          <p><strong>Korrespondent:</strong> <%= doc.correspondent || 'Nicht zugewiesen' %></p>
        </div>
      <% }); %>
    <% } else { %>
      <p>Keine Dokumente gefunden.</p>
    <% } %>
  </div>
</div>
```

**Comment by schergr** [comment]
> @schergr I implemented some features like:
> 
> * Prefill Prompt (example prompt that can be altered) with the improvement of using the language of the document for tags and title.
> * The user can choose a desired OpenAI Model (GPT-3.5, GPT-4o, GPT-4o-mini)
> 
> The docker container is also updated. Maybe you can give it a try?

Sure. Happy to.

**Comment by schergr** [comment]
> > @schergr I implemented some features like:
> > 
> > * Prefill Prompt (example prompt that can be altered) with the improvement of using the language of the document for tags and title.
> > * The user can choose a desired OpenAI Model (GPT-3.5, GPT-4o, GPT-4o-mini)
> > 
> > The docker container is also updated. Maybe you can give it a try?
> 
> Sure. Happy to.

Question...if I don't delete the tags and correspondents already in paperless before I download the new container, will it cause issues. In other words, do you store the tags that you create somewhere else, or do you query the paperless tag list for matches so you don't create dupes.

**Comment by clusterzx** [comment]
Good question! The processed documents will be stored inside a SQLite3 DB within the container. Only the ID of the processed document is stored. 

For example if you run paperless-ai for the first time it will tag all documents and store the id as done. When you delete the container and re run as fresh installation of paperless-ai then the exisiting tags in papeless-ngx will not be touched. Instead it will add new tags and change only the title. So the old tags remain existent. Because the memory of what is already processed is only stored inside the container itself.

**Comment by schergr** [comment]
> Good question! The processed documents will be stored inside a SQLite3 DB within the container. Only the ID of the processed document is stored.
> 
> For example if you run paperless-ai for the first time it will tag all documents and store the id as done. When you delete the container and re run as fresh installation of paperless-ai then the exisiting tags in papeless-ngx will not be touched. Instead it will add new tags and change only the title and correspondet (if the AI finds a new variant). So the old tags remain existent. Because the memory of what is already processed is only stored inside the container itself.
> 
> But it checks on creation of the tag if it already exists to prevent running in issues with the paperless-ngx api.

So if it looks at a new document, and says hey, here's a tag, but that tag already exists in paperless, it won't try to create a new instance of that tag? It will just apply the exisitng one?

**Comment by schergr** [comment]
Still spitting out German tags and titles. less so, but still doing that. The document that it categorized this way had nothing in German about it at all.

**Comment by schergr** [comment]
> Still spitting out German tags and titles. less so, but still doing that. The document that it categorized this way had nothing in German about it at all.

I downloaded the update, and also used your suggested prompt. Still using German. Can you change the tags in the code to be in enslish as well?  
![image](https://github.com/user-attachments/assets/0382d42d-1282-478c-a9ed-cad7713788e8)

**Comment by clusterzx** [comment]
Sorry you have to clarify something for me. Do you mean with German only this text you showed in the snippet you posted here?

**Comment by schergr** [comment]
Well, both actually.  But I'm wondering if that has anything to do with it.

**Comment by clusterzx** [comment]
There is no way that it is an error caused by the actual code. 

If you use docker make sure to delete the container and the image and pull it new. 

Also try it with a test environment with a freshly paperless instance. Maybe it has something to do that the documents are flagged now as German?

I tried with a test instance only with English documents. There was nothing German in the result.

**Comment by cirrusflyer** [comment]
I'm seeing the German as well.

**Comment by cirrusflyer** [comment]
It's tagging correctly, but all the tags listed  on the documents display as "private".  But when I view my tags list, I do see the tags that have been created.

**Comment by cirrusflyer** [comment]
German seems to be fixed now with latest update.  Thanks!
